# /Sources/Coordinator/Implementation/.swiftlint.yml

custom_rules:
  no_public_in_implementation:
    name: "Internal Implementation Only"
    regex: '\bpublic\b'
    match_kinds:
      - attribute.builtin
      - keyword
    message: "Public is forbidden in Implementation folders."
    severity: error
